name:                nix-bikeshed
version:             0.1.0.0
github:              "Ekleog/nix-bikeshed"
license:             BSD3
author:              "Leo Gaspard"
maintainer:          "nix-bikeshed@leo.gaspard.io"
copyright:           "2018 Leo Gaspard"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/Ekleog/nix-bikeshed#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.5 && < 0.6
- data-fix >= 0.2 && < 0.3
- hnix >= 0.4 && < 0.5
- hspec >= 2.5 && < 3
- text >= 1.2 && < 2

library:
  source-dirs: src

executables:
  nix-bikeshed:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nix-bikeshed

tests:
  nix-bikeshed-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nix-bikeshed
